version: "3.3"
services:
  csvserver:
    image: infracloudio/csvserver:latest
    ports:
      - "9393:9300"
  prometheus:
    image: prom/prometheus:v2.22.0
    container_name: csvserver
    volumes:
      - ./config:/prometheus:Z
    command:
      - '--config.file=/prometheus/prometheus.yml'
    ports:
      - 9090:9090
